apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api-gateway
  targetCPUUtilizationPercentage: 50

  #k autoscale deployment api-gateway --cpu-percent 50 --min 1 --max 4