apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: new-joiner
  namespace: default
rules:
  - apiGroups: ["","apps"] #Core API and Apps
    resources: ["*"]
    verbs: ["get","list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: new-joiner-user
  namespace: default
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
subjects: #List all the users who go into the role
  - kind: User
    name: francis-linux-login-name